services:
  redis:
    image: redis:7
    ports:
      - "26379:6379"

  backend:
    build: ./backend
    ports:
      - "28000:8000"
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "25173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

  celery_worker:
    build: ./backend
    command: celery -A celery_worker.celery_app worker --loglevel=info
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./backend:/app

  celery_beat:
    build: ./backend
    command: celery -A celery_worker.celery_app beat --loglevel=info
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./backend:/app
