"""partial unique indexes for soft-deleted domain and email

Revision ID: 41f26a05feb7
Revises: a7d5faf6cbb5
Create Date: 2026-08-04 11:32:41.580904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '41f26a05feb7'
down_revision: Union[str, None] = 'a7d5faf6cbb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sites_domain_key'), 'sites', type_='unique')
    op.create_index('uq_sites_domain_active', 'sites', ['domain'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index('uq_users_email_active', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_email_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_sites_domain_active', table_name='sites', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('sites_domain_key'), 'sites', ['domain'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
