"""add post variant columns

Revision ID: 692a4c165109
Revises: b327da4d8cdc
Create Date: 2026-08-05 10:08:40.233698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '692a4c165109'
down_revision: Union[str, None] = 'b327da4d8cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('variant_group_id', sa.UUID(), nullable=True))
    op.add_column('posts', sa.Column('variant_label', sa.String(length=1), nullable=True))
    op.create_index(op.f('ix_posts_variant_group_id'), 'posts', ['variant_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_variant_group_id'), table_name='posts')
    op.drop_column('posts', 'variant_label')
    op.drop_column('posts', 'variant_group_id')
    # ### end Alembic commands ###
