"""add platform credentials table

Revision ID: b327da4d8cdc
Revises: 41f26a05feb7
Create Date: 2026-08-04 15:57:44.242723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b327da4d8cdc'
down_revision: Union[str, None] = '41f26a05feb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_credentials',
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_credentials')
    # ### end Alembic commands ###
